### ISSUE TITLE
comments fail to parse

### ISSUE THREAD

**Issue by herkhinah** [madman-bob/idris2-xml#1]
[wayland.xml](https://gitlab.freedesktop.org/wayland/wayland/-/raw/8135e856ebd79872f886466e9cee39affb7d9ee8/protocol/wayland.xml)  fails to parse:

```
main : IO ()
main = do
  Right fileContent <- readFile "./wayland.xml"
    | err => printLn err
  let Right (xml, _) = parse xmlDocument fileContent
    | err => printLn err
  printLn $ mapContent deEmphasize xml
  pure ()
  where
    deEmphasize : Element -> Element
    deEmphasize = mapContent $ \content => Snd.do
        elem <- map deEmphasize content
        case show elem.name of
            "em" => elem.content
            _ => pure elem
```

The code errors with `Left "Parse failed at position 271-2: XML document"`

**Comment by herkhinah** [comment]
I've investigated into what exactly doesn't parse and it's the `<!--` `--!>`comments, Installed via pack.

**Comment by madman-bob** [comment]
I've now added support for comments, in version 1.0.
